# Generated by Django 4.2.10 on 2024-03-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_fully_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
