# Generated by Django 4.2.10 on 2024-03-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
