# Generated by Django 4.2.11 on 2024-03-11 12:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_room_capacity_room_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentroom',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
